In [ ]:
import os

for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/datasets/kaushiksuresh147/formula-1-trending-tweets/F1_tweets.csv

In [2]:

import pandas as pd

# Load the dataset
df = pd.read_csv('/kaggle/input/datasets/kaushiksuresh147/formula-1-trending-tweets/F1_tweets.csv')

/tmp/ipykernel_17/1580480156.py:4: DtypeWarning: Columns (5,6,7,12) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/kaggle/input/datasets/kaushiksuresh147/formula-1-trending-tweets/F1_tweets.csv')

In [3]:
# first 5 rows
df.head()

,user_name,user_location,user_description,user_created,user_followers,user_friends,user_favourites,user_verified,date,text,hashtags,source,is_retweet
0,Zack Shephard,NaN,My opinions are mine ALONE. Venting is the onl...,2011-12-03 20:36:55,89.0,2598,212886,False,2021-08-01 23:59:18,The next great #F1 duo!!! @ESPNF1 https://t.co...,['F1'],Twitter for iPhone,False
1,Matteo Vannucci,NaN,"Free speech, free ideas, random thoughts",2010-05-28 01:02:32,10.0,40,8,False,2021-08-01 23:59:10,@F1 What if…Hamilton would have gone to the pi...,"['HungarianGP', 'F1']",Twitter for iPhone,False
2,Michelle,The Burbs,"likes- movies, candy, being lazy, formula 1, ...",2009-03-04 16:53:13,231.0,110,428,False,2021-08-01 23:58:48,This has been a tiring #f1 day... https://t.co...,['f1'],Twitter for Android,False
3,JoshWFC 🇧🇷,NaN,| JP10’s biggest fan | pronouns : João/Pedro |...,2021-04-05 16:14:53,156.0,443,2994,False,2021-08-01 23:58:11,Valteri Bottass tracking down Max Verstappen o...,['F1'],Twitter for iPhone,False
4,Ria Tagulinao,MNL,Fun-sized Filipina writer @Medium,2009-06-22 16:08:51,833.0,379,30891,False,2021-08-01 23:57:40,No words to describe the #HungarianGP so I wil...,"['HungarianGP', 'F1']",Twitter for iPhone,False

In [4]:
#Dataset size 
df.shape

(632388, 13)

In [5]:
# column names and data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 632388 entries, 0 to 632387
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   user_name         632382 non-null  object
 1   user_location     443577 non-null  object
 2   user_description  592917 non-null  object
 3   user_created      632388 non-null  object
 4   user_followers    632388 non-null  float64
 5   user_friends      632388 non-null  object
 6   user_favourites   632388 non-null  object
 7   user_verified     632388 non-null  object
 8   date              632388 non-null  object
 9   text              632388 non-null  object
 10  hashtags          632360 non-null  object
 11  source            632384 non-null  object
 12  is_retweet        632384 non-null  object
dtypes: float64(1), object(12)
memory usage: 62.7+ MB

In [6]:
#  summary statistics
df.describe()

       user_followers
count    6.323880e+05
mean     4.558194e+04
std      4.903496e+05
min      0.000000e+00
25%      1.070000e+02
50%      4.380000e+02
75%      2.039000e+03
max      2.409611e+07